apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    app.owner: huqianghui0613@163.com
    app.date: 20210330 10:28
  labels:
    app.kubernetes.io/name: test-spring-cloud-apps
    app.kubernetes.io/version: 1.0-RELEASE
  name: test-spring-cloud-apps-rolebindings
  namespace: test-ns
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: test-spring-cloud-apps-role
subjects:
  - kind: ServiceAccount
    name: test-spring-cloud-apps-sa