kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: e-sales-ns
  name: e-sales-spring-cloud-apps-role
rules:
  - apiGroups: ["", "extensions", "apps"]
    resources: ["configmaps", "pods", "services", "endpoints", "secrets"]
    verbs: ["get", "list", "watch"]