apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    app.owner: zousb@vanke.com
    app.date: 20210330 10:28
  labels:
    app.kubernetes.io/name: e-sales-spring-cloud-apps
    app.kubernetes.io/version: 1.0-RELEASE
  name: e-sales-spring-cloud-apps-rolebindings
  namespace: e-sales-ns
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: e-sales-spring-cloud-apps-role
subjects:
  - kind: ServiceAccount
    name: e-sales-spring-cloud-apps-sa