apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    app.owner: zousb@vanke.com
    app.date: 20210330 10:28
  labels:
    app.kubernetes.io/name: e-sales-spring-cloud-apps
    app.kubernetes.io/version: 1.0-RELEASE
  name: e-sales-spring-cloud-apps-sa
  namespace: e-sales-ns