apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    app.owner: huqianghui0613@163.com
    app.date: 20210330 10:28
  labels:
    app.kubernetes.io/name: test-spring-cloud-apps
    app.kubernetes.io/version: 1.0-RELEASE
  name: test-spring-cloud-apps-sa
  namespace: test-ns